### ISSUE TITLE
flannel: use the right backend

### ISSUE THREAD

**Issue by mssola** [kubic-project/salt#2]
Right now flannel always uses the UDP backend. That means using overlay + a custom encapsulation protocol. We should change this approach to:

- libvirtd: use host-gw (plain routing): this makes debugging easier and grants better performances
- openstack: use vxlan because it's the fastest overlay driver (encapsulation/decapsulation is done in kernel space, not in userspace like with UDP)

It would be better to make this configurable through a pillar.

**Comment by inercia** [comment]
It is already configurable through [a pillar value](https://github.com/kubic-project/salt/blob/master/pillar/params.sls#L42)
