### ISSUE TITLE
Do not link certificate's CN to anything technical (like domain name)

### ISSUE THREAD

**Issue by ereslibre** [kubic-project/salt#32]
There's no need to do anything like this when setting the `CN` on the `CA` certificate:

```
{% if salt['grains.get']('domain', '')|length > 0 %}
    - CN: {{ grains['domain'] }}
{% elif salt['pillar.get']('dns:domain', '')|length > 0 %}
    - CN: {{ pillar['dns']['domain'] }}
{% else %}
    - CN: kubernetes
{% endif %}
```

From: https://github.com/kubic-project/salt/blob/8e123e4cc8c7308cc55f69ade7ba97009fe265c6/salt/ca/init.sls#L57-L63

Maybe we can use `pillar['certificate_information']['subject_properties']['O']`, or add a different setting. A static `Kubernetes cluster CA certificate` or something similar would work too. Some examples of `CN` values on root certificates:

- https://www.geotrust.com/resources/root-certificates/ (`GeoTrust Primary Certification Authority`, `GeoTrust Primary Certification Authority - G2`...)
- https://www.thawte.com/roots/ (`thawte Primary Root CA`, `thawte Primary Root CA - G2`...)
- https://www.symantec.com/theme/roots (`VeriSign Class 3 Public Primary CA - G2`, `VeriSign Class 3 Public Primary CA`...)

**Comment by inercia** [comment]
You mean that the CN should not be a domain but some descriptive text? Then we can try to get one (in this order): 

* get it from some pillar value (so the user can define their own value)
* build a text description like `CaaSP Kubernetes running on {{ pillar['dns']['domain'] }}`
* use `CaaSP Kubernetes`

Maybe I'm wrong, but I think the CN is not so important...

**Comment by inercia** [comment]
Looking at [this explanation on what a CN name is](https://support.dnsimple.com/articles/what-is-common-name/), it seems **it must be a domain**.

**Comment by ereslibre** [comment]
The `CN` is not really important for a `CA` certificate, it should be a domain for a certificate that will be used for services (but this certificate is only used for creating other certificates and building a chain of trust -- thus, the `CN` on this `CA` certificate is not really used for anything).

**Comment by ereslibre** [comment]
This `CA` certificate could be understood as our own `root` certificate (I posted some links on how some companies set their `Common Name` on their `root` certificates).

**Comment by inercia** [comment]
The I would leave it as it is instead of adding an exception for the `CN` in the root...

**Comment by kiall** [comment]
This was changed a while back!
