### ISSUE TITLE
The new pillar returns None for unset values

### ISSUE THREAD

**Issue by inercia** [kubic-project/salt#326]
The new pillar does not conform to the Salt pillar standard, so `salt['pillar.get']('something:that:does:not:exist', 'default-value')` will never return `'default-value'` but `None`.

**Comment by ereslibre** [comment]
The new pillar is just an override that is merged with the existing one, I wonder why this is happening.

Does `something:that:does:not:exist` exist in the pillar override as `null`? If that's the case, the `default-value` won't be applied as the pillar override **has** the key, and is set to null.

If `something:that:does:not:exist` does not exist in the static pillar nor in the pillar override, `default-value` should be used.

I will have a look as soon as I can.

**Comment by ereslibre** [comment]
This has been fixed.
