### ISSUE TITLE
when using casp as an image a non existing repository gets added

### ISSUE THREAD

**Issue by MaximilianMeister** [kubic-project/salt#35]
it's a mix between opensuse and the casp version:

```
minion0:~ # zypper lr -u
Repository priorities are without effect. All enabled repositories share the same priority.

# | Alias      | Name       | Enabled | GPG Check | Refresh | URI                                                                                    
--+------------+------------+---------+-----------+---------+----------------------------------------------------------------------------------------
1 | containers | containers | Yes     | (  ) No   | Yes     | http://download.opensuse.org/repositories/Virtualization:/containers/openSUSE_Leap_1.0/
```

therefore the comment above https://github.com/kubic-project/salt/blob/master/salt/repositories/containers.repo#L8 is not really true

**Comment by ereslibre** [comment]
This got changed on https://github.com/kubic-project/salt/commit/45dc75ece636f7b64bb34aa0879d6d644694c771

Maybe we can keep the `-{% if grains['oscodename'].startswith("openSUSE Leap") %}`, no?

**Comment by MaximilianMeister** [comment]
> Maybe we can keep the -{% if grains['oscodename'].startswith("openSUSE Leap") %}, no?

i think so, thanks for the hint

**Comment by inercia** [comment]
It is not important that the repo does not make sense as CaaSP does not use repos.
