### ISSUE TITLE
salt orchestration fails

### ISSUE THREAD

**Issue by jgleissner** [kubic-project/salt#425]
When I run the salt orchestration to bootstrap a cluster, I get the following error:

          ID: etcd-setup
    Function: salt.state
      Result: False
     Comment: Run failed on minions: caasp-node-afc4cf66, caasp-node-75b6cb18, caasp-node-f31e8f4a
              Failures:
                  caasp-node-afc4cf66:
                      Data failed to compile:
                  ----------
                      Rendering SLS 'base:ca-cert' failed: Jinja variable list object has no element 0
                  ----------
                      Rendering SLS 'base:cert' failed: Jinja variable list object has no element 0
                  /var/cache/salt/minion/files/base/_macros/certs.jinja(68):
                  ---
                  [...]
                        - file: /etc/pki
                  
                  {{ crt }}:
                    caasp_retriable.retry:
                      - target: x509.certificate_managed
                      - ca_server: {{ salt['mine.get']('roles:ca', 'ca.crt', expr_form='grain').keys()[0] }} <======================
                      - signing_policy: minion
                      - public_key: {{ key }}
                    {%- if cn %}
                      - CN: {{ cn|yaml_dquote }}
                    {%- else %}
                  [...]
                  ---

It appears the mine.get call does not return the certificate as intended. And in fact, if I call `salt-call mine.get 'roles:ca' ca.crt grain` I get nothing back. Using 'ca' instead of 'roles:ca' works. Running `salt ca mine.get 'roles:ca' ca.crt grain` on the salt master also returns the certificate.

Any idea?

**Comment by inercia** [comment]
Do you still have the orchestration output? Maybe we could see why that certificate was not generated... It would also be useful to take a look at the Salt Master output, maybe it is failing some communication channel...

**Comment by ereslibre** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [salt orchestration fails](https://trello.com/c/6orCy2Bv/716-salt-orchestration-fails)

**Comment by jgleissner** [comment]
I was trying to reproduce it for a full log, but now I'm running into a slightly different error:
```14:47:13,604 [ERROR   ] Exception during resolving address: [Errno 1] Unknown host
14:47:13,605 [ERROR   ] Exception during resolving address: [Errno 1] Unknown host
14:47:13,607 [ERROR   ] Exception during resolving address: [Errno 1] Unknown host
14:47:13,609 [ERROR   ] Exception during resolving address: [Errno 1] Unknown host
14:47:13,610 [ERROR   ] Exception during resolving address: [Errno 1] Unknown host
14:47:13,626 [DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
14:47:13,626 [DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
14:47:13,641 [DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
14:47:13,643 [DEBUG   ] Sending event: tag = salt/run/20180315144713625929/new; data = {'fun': 'runner.mine.get', 'fun_args': [{'fun': 'nodename', 'tgt_type': 'compound', 'tgt': 'G@roles:kube-minion and not G@roles:etcd'}], 'jid': '20180315144713625929', 'user': 'UNKNOWN', '_stamp': '2018-03-15T14:47:13.643016'}
14:47:13,646 [DEBUG   ] _check_compound_minions(G@roles:kube-minion and not G@roles:etcd, :, True, False)
14:47:13,648 [DEBUG   ] minions: set(['admin', 'ca', 'caasp-node-9a77639d', 'caasp-node-8530ff4c', 'caasp-node-9f00ceaa'])
14:47:13,649 [DEBUG   ] LazyLoaded localfs.init_kwargs
14:47:13,650 [DEBUG   ] Attempting to match 'kube-minion' in 'roles' using delimiter ':'
14:47:13,651 [DEBUG   ] Attempting to match 'kube-minion' in 'roles' using delimiter ':'
14:47:13,652 [DEBUG   ] Attempting to match 'kube-minion' in 'roles' using delimiter ':'
14:47:13,652 [DEBUG   ] Attempting to match 'kube-minion' in 'roles' using delimiter ':'
14:47:13,653 [DEBUG   ] Attempting to match 'kube-minion' in 'roles' using delimiter ':'
14:47:13,653 [DEBUG   ] Attempting to match 'etcd' in 'roles' using delimiter ':'
14:47:13,654 [DEBUG   ] Attempting to match 'etcd' in 'roles' using delimiter ':'
14:47:13,655 [DEBUG   ] Attempting to match 'etcd' in 'roles' using delimiter ':'
14:47:13,655 [DEBUG   ] Attempting to match 'etcd' in 'roles' using delimiter ':'
14:47:13,656 [DEBUG   ] Attempting to match 'etcd' in 'roles' using delimiter ':'
14:47:13,656 [DEBUG   ] Evaluating final compound matching expr: set(['caasp-node-9f00ceaa', 'caasp-node-9a77639d']) & ( set(['admin', 'ca', 'caasp-node-9a77639d', 'caasp-node-8530ff4c', 'caasp-node-9f00ceaa']) - set([]) )
14:47:13,657 [DEBUG   ] LazyLoaded localfs.init_kwargs
14:47:13,657 [DEBUG   ] Cache file "/var/cache/salt/master/minions/caasp-node-9f00ceaa/mine.p" does not exist
14:47:13,658 [DEBUG   ] Cache file "/var/cache/salt/master/minions/caasp-node-9a77639d/mine.p" does not exist
14:47:13,658 [DEBUG   ] Sending event: tag = salt/run/20180315144713625929/ret; data = {'fun_args': [{'fun': 'nodename', 'tgt_type': 'compound', 'tgt': 'G@roles:kube-minion and not G@roles:etcd'}], 'jid': '20180315144713625929', 'return': {}, 'success': True, '_stamp': '2018-03-15T14:47:13.658337', 'user': 'UNKNOWN', 'fun': 'runner.mine.get'}
14:47:13,661 [DEBUG   ] LazyLoaded local_cache.prep_jid
14:47:13,662 [INFO    ] Runner completed: 20180315144713625929
14:47:13,663 [DEBUG   ] CaaS: get_additional_etcd_members: taking 0 minions -> 1 missing
14:47:13,663 [ERROR   ] CaaS: get_additional_etcd_members: cannot satisfy the 1 members missing
14:47:13,664 [ERROR   ] Rendering exception occurred: Jinja variable No first item, sequence was empty.
14:47:13,665 [CRITICAL] Rendering SLS 'base:orch.kubernetes' failed: Jinja variable No first item, sequence was empty.
14:47:13,665 [DEBUG   ] Sending event: tag = salt/run/20180315144452065771/ret; data = {'fun_args': ['orch.kubernetes', {'orchestration_jid': '20180315144452065771'}], 'jid': '20180315144452065771', 'return': {'outputter': 'highstate', 'data': {'caasp-test_master': ["Rendering SLS 'base:orch.kubernetes' failed: Jinja variable No first item, sequence was empty."]}, 'retcode': 1}, 'success': False, '_stamp': '2018-03-15T14:47:13.665706', 'user': 'root', 'fun': 'runner.state.orchestrate'}
14:47:13,667 [DEBUG   ] LazyLoaded highstate.output
caasp-test_master:
    Data failed to compile:
----------
    Rendering SLS 'base:orch.kubernetes' failed: Jinja variable No first item, sequence was empty.
14:47:13,668 [DEBUG   ] LazyLoaded local_cache.prep_jid
14:47:13,669 [INFO    ] Runner completed: 20180315144452065771
14:47:13,669 [DEBUG   ] Runner return: {'outputter': 'highstate', 'retcode': 1}
````
I can get you the full log if you like. I'm wondering whether the exception when trying to resolve a host is what's going wrong here. It doesn't actually say which host name it tries to resolve.

**Comment by ereslibre** [comment]
```
caasp-test_master:
    Data failed to compile:
----------
    Rendering SLS 'base:orch.kubernetes' failed: Jinja variable No first item, sequence was empty.
14:47:13,668 [DEBUG   ] LazyLoaded local_cache.prep_jid
14:47:13,669 [INFO    ] Runner completed: 20180315144452065771
14:47:13,669 [DEBUG   ] Runner return: {'outputter': 'highstate', 'retcode': 1}
```

The problem here is `Rendering SLS 'base:orch.kubernetes' failed: Jinja variable No first item, sequence was empty.`. A list was expected somewhere, but nothing was there.

The `Unknown host` error is unrelated, and introduced here: https://build.suse.de/package/rdiff/SUSE:SLE-12-SP3:Update/salt?linkrev=base&rev=14 by the patch feat-add-grain-for-all-fqdns.patch.

I think having an issue open for a failed orchestration is way too generic. The last orchestration error has nothing to do with the first one, and on the first one it looks like the ca salt-minion didn't execute its mine publishing commands on startup:

https://github.com/kubic-project/salt/blob/292b025681915a6ad4d7378624385d231f2f21d4/pillar/ca.sls

I'd propose to close this bug since as I say it's too generic and we can end up discussing complete different orchestration outputs as we go because the orchestration fails.

**Comment by inercia** [comment]
I agree with @ereslibre. Closing...
