### ISSUE TITLE
Break the kubernetes-minion state in smaller components

### ISSUE THREAD

**Issue by inercia** [kubic-project/salt#48]
At some moment we will install the `kubelet` in all the machines (including the masters), and maybe the `proxy` will be run as a daemon set, so it would be good to split this state in several states (ie, `kubelet` and `proxy`) and add the `kubelet` to the `role:kube-master`

**Comment by grahamhayes** [comment]
And if we want to add additional services (like fluentd for logging, or a DNS server for when we scale out) having `kubelet` on the masters would be very useful

**Comment by robdaemon** [comment]
I'm actually doing some of this work as part of adding haproxy...

**Comment by kiall** [comment]
This has been done
