### ISSUE TITLE
etcd traffic should be using https only

### ISSUE THREAD

**Issue by robdaemon** [kubic-project/salt#54]
Currently, we're configuring etcd to use HTTP and HTTPS, which is a security concern. You also see errors in the etcd logs:

```
May 01 18:37:30 minion1 etcd[2613]: The scheme of client url http://0.0.0.0:2379 is HTTP while peer key/cert files are presented. Ignored key/cert files.
```

See `/etc/sysconfig/etcd`:

```
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
ETCD_LISTEN_PEER_URLS="https://0.0.0.0:2380"

ETCD_ADVERTISE_CLIENT_URLS="http://minion1.k8s.local:2379,http://10.17.3.187:2379"
```

That must all be https.

**Comment by robdaemon** [comment]
@ukbelch - you'll be interested in this one.

**Comment by ereslibre** [comment]
The idea is that between etcd members traffic goes through https, but since every node contains its own etcd member or proxy the services contacting etcd locally can use raw http (traffic is local in this case always) by using localhost. This allows us to consume less cpu in this specific case. 

We might want to revisit this though anyways.

**Comment by robdaemon** [comment]
I can understand that idea, but many banks will not accept any insecure traffic, even if it's on localhost, but if we decided that was okay, we shouldn't have a listen on http://0.0.0.0:2379.

**Comment by ereslibre** [comment]
I remember we had a problem documented here: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md (documentation on `--advertise-client-urls`). We had an infinite loop and etcd ran out of fd's. 

```
Be careful if advertising URLs such as http://localhost:2379 from a cluster member and are using the proxy feature of etcd. This will cause loops, because the proxy will be forwarding requests to itself until its resources (memory, file descriptors) are eventually depleted.
```

But yes, I agree is worth revisiting the issue. Just wanted to provide some context.

**Comment by PI-Victor** [comment]
closing this as it was fixed. https://github.com/kubic-project/salt/blob/master/salt/etcd/etcd.conf.jinja
if there are any leftovers related, feel free to reopen it.
