### ISSUE TITLE
increase number of salt worker threads?

### ISSUE THREAD

**Issue by PI-Victor** [kubic-project/salt#62]
The bootstrapping process never finishes, it seems i hit this while trying to bootstrap 5 nodes
https://github.com/saltstack/salt/issues/27421

here's the [log dump of the salt master](http://pastebin.suse.de/17171)

**Comment by ereslibre** [comment]
I am hitting this problem with 2 nodes after trying to execute a clean run of the e2e tests, and I already have the 10 `worker_threads` setting.

**Comment by ereslibre** [comment]
NVM, I was referring to this error that I am getting consistently now (not sure if this happened before, but I don't think so):

`Received function _file_find which is unavailable on the master, returning False`

**Comment by PI-Victor** [comment]
yeah, i get that error all the time. i actually found some fix for it, but it's some hacky thing where you add that `_file_find` function just so that you can squash the notification. i remember looking into it some time ago.
