### ISSUE TITLE
Use the salt.modules.etcd_mod module

### ISSUE THREAD

**Issue by inercia** [kubic-project/salt#64]
We are doing many operations on `etcd` in different parts of our code (ie, for setting the etcd discovery or for configuring flannel). Most of these things are done with the help of `etcdctl` or `curl`, but there is a native mechanism with the [`salt.modules.etcd_mod`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.etcd_mod.html) module. We should try to use it, but it would require packaging `python-etcd` and including it in the CaaSP image...

**Comment by inercia** [comment]
@jordimassaguerpla What do you think about this?

**Comment by jordimassaguerpla** [comment]
@inercia : from a package perspective sounds good. This package has just a couple of dependencies and it is not tight to specific versions.

The only doubt is whether you will be eager to be the maintainer of this package (I know you already packaged that :) ).

**Comment by inercia** [comment]
@jordimassaguerpla I didn't package `python-etcd` and I did not plan to be maintainer of that... I could be the maintainer if nobody else wants to do that.

**Comment by mjura** [comment]
@inercia, @jordimassaguerpla: ok, as we discussed on standup meeting this package is needed for me to develop salt etcd grain module. I will take care of building this image from repo.

**Comment by mjura** [comment]
https://build.opensuse.org/request/show/496243

**Comment by mjura** [comment]
https://build.opensuse.org/request/show/496479

**Comment by stefsuse** [comment]
This issue is 1.5 years old
