### ISSUE TITLE
Use salt.modules.haproxyconn for managing haproxy

### ISSUE THREAD

**Issue by inercia** [kubic-project/salt#65]
Maybe we could use [this Salt module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.haproxyconn.html) for managing haproxy instead of [manually regenerating configs and `kill -HUP`ing](https://github.com/kubic-project/salt/blob/ha/salt/haproxy/init.sls)...

CC: @robdaemon

**Comment by robdaemon** [comment]
We'd still need to write the configuration file so that a restart of haproxy would have the right configuration, and then expose the haproxy unix socket on a hostPath. This doesn't really buy us anything.

**Comment by inercia** [comment]
> We'd still need to write the configuration file so that a restart of haproxy would have the right configuration, and then expose the haproxy unix socket on a hostPath. This doesn't really buy us anything.

Writing a config file is not strictly necessary as you are going to create your own haproxy image based on SLE, so a base config file could be `COPY`ed there.

I think the main difference would in how we deal with machines that go down/up or change IPs. Instead of applying a full state you would do something like:

```
# FILE: config.d/master/reactor.conf
  - salt/presence/change:
    - /usr/share/salt/kubernetes/reactor/presence.sls

# FILE: config.d/master/presence.sls
{% for machine_down in data['lost'] %}
{%- set api_servers = salt['pillar.get']('roles:kube-master', '') %}
{% if machine_down in api_servers %}
remove-{{machine-down}}-from-haproxy:
  module.wait:
    - tgt: 'roles:kube-minion'
    - tgt_type: grain
    - name: haproxyconn.disable_server
    - backend: api
    - name: {{ machine_down }}
{% endif %}
{% endfor %}
```

That would save the config file regeneration, `SIGHUP` and so...

**Comment by robdaemon** [comment]
Not really, you still need the configuration file if haproxy gets restarted for any reason (it crashes, the node reboots, etc.) This would just complicate things.
