### ISSUE TITLE
Pillar override does not allow for unitary lists

### ISSUE THREAD

**Issue by ereslibre** [kubic-project/salt#75]
We are using the external pillar override using mysql, where lists are interpreted as collisions. This has an important drawback on our case, and is that we lose the ability to represent unitary lists on the current implementation.

https://github.com/kubic-project/salt/blob/bace710019cc5bd7f7fcc175597c8057e15142d5/config/master.d/returner.conf#L54-L76

This will be read by salt as a value if no key collision happens, but a collision needs at least two values. In this situation we cannot represent unitary lists.

We should fix this in a way that the queries are crafted in a way that this is possible.

**Comment by ereslibre** [comment]
This issue will be fixed by https://github.com/kubic-project/salt/pull/238

**Comment by inercia** [comment]
Fixed
